from django.urls import path

from . import views

from .helper import startup

# Initialize session
startup()

urlpatterns = [
path('', views.index, name='index'),
path('login', views.login, name='login'),
path('news/', views.news, name='news'),
path('links/', views.links, name='links'),
path('active_sites/', views.active_sites, name='active_sites'),
path('forum/', views.forum, name='forum'),
path('ranking/', views.ranking, name='ranking'),
path('challs/', views.challs, name='challs'),
path('downloads/', views.downloads, name='downloads'),
path('register/', views.register, name='register'),
path('about_wechall/', views.about_wechall, name='about_wechall'),
path('users/with/All/by/user_regdate/DESC/page-1/', views.users_with_All_by_user_regdate_DESC_page_1, name='users_with_All_by_user_regdate_DESC_page_1'),
path('profile/MojitoLimeDouble/', views.profile_MojitoLimeDouble, name='profile_MojitoLimeDouble'),
path('profile/AlexKOX/', views.profile_AlexKOX, name='profile_AlexKOX'),
path('profile/clolcat/', views.profile_clolcat, name='profile_clolcat'),
path('profile/desencrypt/', views.profile_desencrypt, name='profile_desencrypt'),
path('profile/LaTD/', views.profile_LaTD, name='profile_LaTD'),
path('profile/c3cili4/', views.profile_c3cili4, name='profile_c3cili4'),
path('profile/frijess98/', views.profile_frijess98, name='profile_frijess98'),
path('profile/sshi/', views.profile_sshi, name='profile_sshi'),
path('users/with/All/by/user_lastactivity/DESC/page-1/', views.users_with_All_by_user_lastactivity_DESC_page_1, name='users_with_All_by_user_lastactivity_DESC_page_1'),
path('profile/Guest/', views.profile_Guest, name='profile_Guest'),
path('profile/a_robles/', views.profile_a_robles, name='profile_a_robles'),
path('profile/dvnunes/', views.profile_dvnunes, name='profile_dvnunes'),
path('profile/Elian/', views.profile_Elian, name='profile_Elian'),
path('profile/gizmore/', views.profile_gizmore, name='profile_gizmore'),
path('profile/livinskull/', views.profile_livinskull, name='profile_livinskull'),
path('profile/lordOric/', views.profile_lordOric, name='profile_lordOric'),
path('profile/New_LucA/', views.profile_New_LucA, name='profile_New_LucA'),
path('profile/tehron/', views.profile_tehron, name='profile_tehron'),
path('profile/tristiny/', views.profile_tristiny, name='profile_tristiny'),
path('profile/zangruochuan/', views.profile_zangruochuan, name='profile_zangruochuan'),
path('profile/zy5451/', views.profile_zy5451, name='profile_zy5451'),
path('recovery/', views.recovery, name='recovery'),
path('users/', views.users, name='users'),
path('donations/', views.donations, name='donations'),
path('profile/dloser/', views.profile_dloser, name='profile_dloser'),
path('profile/benito255/', views.profile_benito255, name='profile_benito255'),
path('profile/Caesum/', views.profile_Caesum, name='profile_Caesum'),
path('profile/jusb3/', views.profile_jusb3, name='profile_jusb3'),
path('profile/phoenix1204/', views.profile_phoenix1204, name='profile_phoenix1204'),
path('profile/Akorlith/', views.profile_Akorlith, name='profile_Akorlith'),
path('profile/thefinder/', views.profile_thefinder, name='profile_thefinder'),
path('profile/yachoor/', views.profile_yachoor, name='profile_yachoor'),
path('profile/SteKap/', views.profile_SteKap, name='profile_SteKap'),
path('profile/TinyMartian/', views.profile_TinyMartian, name='profile_TinyMartian'),
path('profile/tehbot/', views.profile_tehbot, name='profile_tehbot'),
path('profile/Denzel55/', views.profile_Denzel55, name='profile_Denzel55'),
path('profile/TheShade/', views.profile_TheShade, name='profile_TheShade'),
path('profile/tenflo/', views.profile_tenflo, name='profile_tenflo'),
path('profile/LouisJ/', views.profile_LouisJ, name='profile_LouisJ'),
path('profile/rinakawamura/', views.profile_rinakawamura, name='profile_rinakawamura'),
path('profile/ayen2/', views.profile_ayen2, name='profile_ayen2'),
path('profile/djohn364/', views.profile_djohn364, name='profile_djohn364'),
path('profile/B0Jack/', views.profile_B0Jack, name='profile_B0Jack'),
path('profile/charkh/', views.profile_charkh, name='profile_charkh'),
path('join_us/', views.join_us, name='join_us'),
path('irc_chat/', views.irc_chat, name='irc_chat'),
path('contact/', views.contact, name='contact'),
path('wechall_license/', views.wechall_license, name='wechall_license'),
]
